In [1]:
# probability_distributions

In [2]:
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats


# For the following problems, use python to simulate the problem and calculate an experimental probability, then compare that to the theoretical probability.

# 1. A bank found that the average number of cars waiting during the noon hour at a drive-up window follows a Poisson distribution with a mean of 2 cars. Make a chart of this distribution and answer these questions concerning the probability of cars waiting at the drive-up window.

In [3]:
# What is the probability that no cars drive up in the noon hour?
# What is the probability that 3 or more cars come through the drive through?
# How likely is it that the drive through gets at least 1 car?

In [4]:
# .rvs for simulations



In [5]:
# drive through mean 2 cars
# What is the probability that no cars drive up in the noon hour?

stats.poisson(2).pmf(0)

0.1353352832366127

In [6]:
# What is the probability that 3 or more cars come through the drive through?

stats.poisson(2).sf(3) #use .sf for 3 or more 

0.14287653950145296

In [7]:
# # How likely is it that the drive through gets at least 1 car?

stats.poisson(2).pmf(1)

0.2706705664732254

In [8]:
#2 Grades of State University graduates are normally distributed with a mean of 3.0 and a standard deviation of .3. 
# Calculate the following:

# What grade point average is required to be in the top 5% of the graduating class?
# What GPA constitutes the bottom 15% of the class?
# An eccentric alumnus left scholarship money for students in the third decile from the bottom of their class.
# Determine the range of the third decile.
# Would a student with a 2.8 grade point average qualify for this scholarship?
# If I have a GPA of 3.5, what percentile am I in?

In [9]:
# mean 3
# stdv .3
# What grade point average is required to be in the top 5% of the graduating class?
μ = 3
σ = .3

gpa = stats.norm(μ, σ)

top_5_percent = gpa.ppf(.95) # top 5 percent is represented .95


print('{:,.2f}'.format(top_5_percent))

3.49


In [10]:
# What GPA constitutes the bottom 15% of the class?

bottom_15_percent = gpa.ppf(.15)

print('{:,.2f}'.format(bottom_15_percent))

2.69


In [11]:
# Determine the range of the third decile.

thrid_decile = gpa.ppf(.30) - gpa.ppf(.20)
thrid_decile # range of third_decile .0951



0.0951662162594622

In [12]:
# Would a student with a 2.8 grade point average qualify for this scholarship?

gpa.cdf(2.8) # yes they would qualify

0.2524925375469227

In [13]:
gpa.ppf(.2524925375469227)

2.8

In [14]:
# If I have a GPA of 3.5, what percentile am I in?

gpa.cdf(3.5)

0.9522096477271853

In [15]:
gpa.ppf(.90)

3.3844654696633802

In [16]:
#3 A marketing website has an average click-through rate of 2%. One day they observe 4326 visitors and 97 click-throughs. 
# How likely is it that this many people or more click through?

# .02 two percent 
# 4326 visitors
# 97 click throughs

average = .02
# σ = 

one_day = 97/4326

click_through = stats.poisson.sf(one_day, average)
click_through
# print('{:,.2f}'.format(click_through))

0.0198013266932447

In [17]:
print('{:,.2f}'.format(click_through))

0.02


In [45]:
#4 You are working on some statistics homework consisting of 100 questions where all of the answers 
# are a probability rounded to the hundreths place.
# Looking to save time, you put down random probabilities as the answer to each question.

# What is the probability that at least one of your first 60 answers is correct?

# 100 questions
# rounded to the hundreths .01
# 1 in 60 is correct probality

one_sixty = stats.binom(60, 1/100) #60 questions with a chance of 1
hw = one_sixty.pmf(1) + one_sixty.sf(1)
hw

0.4528433576092542

In [46]:
print('{:,.2f}'.format(hw))

0.45


In [63]:
#5 The codeup staff tends to get upset when the student break area is not cleaned up. 
# Suppose that there's a 3% chance that any one student cleans the break area when they visit it, 
# and, on any given day, about 90% of the 3 active cohorts of 22 students visit the break area. 
# How likely is it that the break area gets cleaned up each day? 
# How likely is it that it goes two days without getting cleaned up? All week?

# .03 percent clean one student
# .90 percent visit
# 3 cohorts of 22 students, 66 students
# cleaned each day? 5 days?
# 2 days not cleaned?
# not cleaned all week?

clean_avg = .03
visit = .90 * 66

clean_breakroom = stats.binom(visit, clean_avg).sf(1)
clean_breakroom #cleaned each day

0.5317140258060139

In [21]:
# two days without cleaning

visit_2 = visit * 2 # double the amount of visits because there are 2 days
two_days_dirty = stats.binom(visit_2, clean_avg).pmf(0) # 0 times being cleaned
two_days_dirty

0.026821436301629083

In [22]:
# all week dirty 5? 

visit_5 = visit * 5
five_days_dirty = stats.binom(visit_5, clean_avg).pmf(0)
five_days_dirty

0.00011781621791055144

In [23]:
# all week dirty 7?

visit_7 = visit * 7
seven_days_dirty = stats.binom(visit_7, clean_avg).pmf(0)
seven_days_dirty * 100


0.00031600001839867086

In [37]:
#6 You want to get lunch at La Panaderia, but notice that the line is usually very long at lunchtime. 
# After several weeks of careful observation, you notice that the average number of people in line when your 
# lunch break starts is normally distributed with a mean of 15 and standard deviation of 3. 
# If it takes 2 minutes for each person to order, and 10 minutes from ordering to getting your food, 
# what is the likelihood that you have at least 15 minutes left to eat your food before you have to go back to class? 
# Assume you have one hour for lunch, and ignore travel time to and from La Panaderia.

# average 15 people
# stdv 3 people
# 2 min each person order
# 10 min from order to food
# at least 15 mins to eat
# 1 hour lunch

average_people = 15
stdv = 3
order = 2
food = 10
time_to_eat = 15
lunch = 60 #hour / 60 minutes

order_food = order + food # 12 minutes per person, I do not think I need this

people_in_line = stats.norm(average_people, stdv).cdf(16.5) # people in line at start of lunch ?
people_in_line

# if there are 15 people in line at the start of lunch, it will take them 2 mins each to order 
# 2*15 = 30mins to place an order, 60-30 = 30mins remaining
# 2 mins to place my order 30-2 = 28mins remaining
# 10mins to get food, 28 - 10 = 18mins remaining
# 15mins to eat, 18-15 = 3mins remaining



0.6914624612740131

In [49]:
# Connect to the employees database and find the average salary of current employees, 
# along with the standard deviation. 
# For the following questions, calculate the answer based on modeling the employees salaries with a normal 
# distribution defined by the calculated mean and standard deviation then compare this answer to the actual 
# values present in the salaries dataset.



from env import host, user, password

url = f'mysql+pymysql://{user}:{password}@{host}/employees'

In [50]:

def get_db_url(user,password,host,database):
    
    return f'mysql+pymysql://{user}:{password}@{host}/{database}'

In [51]:
import pandas as pd
from env import user, password, host

pd.read_sql("select * from employees", get_db_url(user, password, host, 'employees'))

emp_no  birth_date first_name last_name gender   hire_date
0        10001  1953-09-02     Georgi   Facello      M  1986-06-26
1        10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2        10003  1959-12-03      Parto   Bamford      M  1986-08-28
3        10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
4        10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12
...        ...         ...        ...       ...    ...         ...
300019  499995  1958-09-24     Dekang  Lichtner      F  1993-01-12
300020  499996  1953-03-07       Zito      Baaz      M  1990-09-27
300021  499997  1961-08-03    Berhard    Lenart      M  1986-04-21
300022  499998  1956-09-05   Patricia   Breugel      M  1993-10-13
300023  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30

[300024 rows x 6 columns]

In [53]:
def get_data_from_sql(user, host, password, database, query):
    
    url = f'mysql+pymysql://{user}:{password}@{host}/{database}'
        
    return pd.read_sql(query, url)

In [68]:
query = '''select * from employees'''

df = get_data_from_sql(user, host, password, "employees", query)

In [65]:
salaries = get_data_from_sql(user, host, password, 'employees', 'select salary from salaries where to_date >= now()')
salaries.head()

salary
0   88958
1   72527
2   43311
3   74057
4   94692

In [72]:
# find the average salary of current employees
avg = salaries.mean()
avg


salary    72012.235857
dtype: float64

In [73]:
# along with the standard deviation
stdv = salaries.std()
stdv

salary    17309.99538
dtype: float64

In [75]:
salary_norml = stats.norm(avg, stdv)

In [84]:
# What percent of employees earn less than 60,000?

salary_norml.cdf(60_000) - salary_norml.pdf(60_000)

array([0.24383931])

In [83]:
# What percent of employees earn more than 95,000?

salary_norml.sf(95_000)

array([0.09208819])

In [82]:
# What percent of employees earn between 65,000 and 80,000?

salary_norml.cdf(80_000) - salary_norml.cdf(65_000)

array([0.33506057])

In [85]:
# What do the top 5% of employees make?

salary_norml.ppf(.95)

array([100484.64454103])

In [86]:
salary_norml.ppf(.99)

array([112281.30680981])

In [88]:
salary_norml.ppf(.9999)

array([136388.39403963])