In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1 How likely is it that you roll doubles when rolling two dice?
outcomes = [1, 2, 3, 4, 5, 6] # six sides of a die

n_simulations = 1_000_000

n_trials = 2 

rolls = np.random.choice(outcomes, size=(n_simulations, n_trials))

rolls[0:5]

array([[6, 1],
       [5, 6],
       [2, 3],
       [3, 4],
       [3, 6]])

In [3]:
doubles = ((rolls.sum(axis=1) == [2, 4, 6, 8, 10, 12]))
doubles

<ipython-input-3-8cfce7ef881d>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  doubles = ((rolls.sum(axis=1) == [2, 4, 6, 8, 10, 12]))


False

In [4]:
# 1 How likely is it that you roll doubles when rolling two dice?
# define each die (die1, die2) then boolaean (die1 == die2)

die_1 = np.random.choice([1,2,3,4,5,6], 1_000_000)
die_2 = np.random.choice([1,2,3,4,5,6], 1_000_000)

(die_1 == die_2).mean()

0.166522

In [5]:
# 2 If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# 'heads', 'tails' can be '1', '0'
 
coin_flip = np.random.choice((0,1), size=(1_000_000, 8)) # choosing at random between 0 and 1, 1 million times with 8 coins
coin_flip[0:5]

array([[0, 0, 0, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 0, 0]])

In [6]:
coin_flip.sum(axis=1) == 3 # where the coin flip is '1' 'heads' 3 times

array([False,  True, False, ..., False, False, False])

In [7]:
(coin_flip.sum(axis=1) == 3).mean() 

0.219981

In [8]:
#2 Continued What is the probability of getting more than 3 heads?
(coin_flip.sum(axis=1) > 3).mean() 

0.635319

In [9]:
# 3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?

# 3 web .75% add this as a weight 
# 1 data .25% add this as a weight
# 2 billboards '0', '1'

# random.choice(a, size=None, replace=True, p=None)

billboards = np.random.choice((0,1), size=(1_000_000, 2), p=(.75, .25))

In [10]:
(billboards.sum(axis=1) == 2).mean() 

0.06257

In [11]:
(1/4)**2

0.0625

In [2]:
#4 Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, 
# how likely is it that I will be able to buy some poptarts on Friday afternoon?

# 3 poptarts (+-1.5) per day
# 7 days or 5 days?
# duration of the day
# +17 poptarts monday
# poptarts on friday ?
# can not have a percent of a poptart ? is there a way to do that

# np.random.normal: generates numbers from a normal distribution with a specified mean and standard deviation
# random.normal(loc=0.0, scale=1.0, size=None)

poptarts = np.random.normal(loc=3, scale=1.5, size=(1_000_000, 5))

In [3]:
# poptarts.sum(axis=1) == 1 # does not need to equal 1

In [4]:

poptarts.sum(axis=1) # what about rounding to whole numbers ??? # astype.integer?

array([10.18828307, 16.02803396, 18.67341707, ..., 11.4901741 ,
       21.13816993, 14.99526758])

In [5]:
(poptarts.sum(axis=1) > 17).mean() # I think this is how likely there will be no poptarts on friday

0.274971

In [6]:
(poptarts.sum(axis=1) < 17).mean() # I think this is how likely there will be poptarts on friday

0.725029

In [16]:
# poptart question using a random.uniform
uniform = np.random.uniform(1.5, 4.5, size=(1_000_000, 5))
(uniform.sum(axis=1) > 17).mean()

0.15639

In [17]:
# 5 Compare Heights

# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, P(woman taller than man)?


# men 178 +-8
# women 170 +-6
# # random.normal(loc=0.0, scale=1.0, size=None)

tall_men = np.random.normal(loc=178, scale=8, size=1_000_000)
tall_women = np.random.normal(loc=170, scale=6, size=1_000_000)
(tall_women > tall_men).mean()

0.212597

In [9]:
#6 When installing anaconda on a student's computer, 
# there's a 1 in 250 chance that the download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

# How likely is it that 450 students all download anaconda without an issue?


# 1 / 250 corrupted
# 50 students no issues
# 100 students no issues

array_1_to_251 = np.arange(start = 1, stop =250)
np.random.choice(a = array_1_to_251, size = 1)
# I dont think I needed these


array([226])

In [10]:
#50 students
no_issue = np.random.choice((0,1), size=(1_000_000, 50), p=(.996, .004))
no_issue

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [11]:
(no_issue.sum(axis=1) == 0)

array([ True,  True,  True, ..., False,  True, False])

In [12]:
(no_issue.sum(axis=1) == 0).mean()

0.818174

In [13]:
#100 students
no_issue_100 = np.random.choice((0,1), size=(1_000_000, 100), p=(.996, .004))
(no_issue_100.sum(axis=1) == 0).mean()

0.670189

In [14]:
249/250

0.996

In [15]:
1/250

0.004

In [16]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?
issue_150 = np.random.choice((0,1), size=(1_000_000, 150), p=(.996, .004))
(issue_150.sum(axis=1) > 0).mean()

0.451505

In [17]:
# How likely is it that 450 students all download anaconda without an issue?
no_issue_450 = np.random.choice((0,1), size=(1_000_000, 450), p=(.996, .004))
(no_issue_450.sum(axis=1) == 0).mean()

0.164805

In [28]:
#7 There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

# .70 chance
# 7 days

food_truck = np.random.choice((0,1), size=(1_000_000, 3), p=(.30, .70))
(food_truck.sum(axis=1) == 0).mean()

0.027366

In [29]:
# How likely is it that a food truck will show up sometime this week?
food_truck_this_week = np.random.choice((0,1), size=(1_000_000, 7), p=(.30, .70))
(food_truck.sum(axis=1) > 0).mean()

0.972634

In [37]:
#8 If 23 people are in the same room, what are the odds that two of them share a birthday? 
# 50 / 50 birthday paradox

# What if it's 20 people? 
# 40?

In [18]:
from random import randint
from datetime import datetime, timedelta

def random_birthdays(number_of_people):
    first_day_of_year = datetime(2000, 1, 1)
    return [first_day_of_year + timedelta(days=randint(0, 365))
            for _ in range(number_of_people)]

In [19]:
def determine_probability(number_of_people, run_amount=1_000):
    dups_found = 0
    for _ in range(run_amount):
        birthdays = random_birthdays(number_of_people)
        duplicates = set(x for x in birthdays if birthdays.count(x) > 1)
        if len(duplicates) >= 1:
            dups_found += 1

    return dups_found/run_amount * 100

In [20]:
if __name__ == '__main__':
    msg = ("{people} Random people have a {chance:.1f}%"
           " chance of having a birthday on the same day")
    for people in (23, 20, 40):
        print(msg.format(people=people, chance=determine_probability(people)))

23 Random people have a 50.9% chance of having a birthday on the same day
20 Random people have a 40.1% chance of having a birthday on the same day
40 Random people have a 89.1% chance of having a birthday on the same day


In [ ]:
### steven's example

folks = 40
n = 10000
matches = 0
samples = np.random.randint(1,366,folks*n).reshape(n,folks)

for s in samples:
	for ix, x in enumerate(s):
		if x in s[ix+1:]:
			matches += 1
			break
print(f"Prob. of a match is {matches/n}")